# Generated by Django 4.1.7 on 2023-03-24 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_id_alter_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchrecord',
            name='product',
        ),
    ]
