# Generated by Django 4.1.7 on 2023-03-24 02:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_watchrecord_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchrecord',
            name='product',
            field=models.ForeignKey(default=datetime.date.today(), on_delete=django.db.models.deletion.CASCADE, to='product.product'),
            preserve_default=False,
        ),
    ]
