# Generated by Django 4.1.7 on 2023-03-24 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_watchrecord_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchrecord',
            name='id',
        ),
        migrations.AlterField(
            model_name='watchrecord',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.product'),
        ),
    ]
